### PR TITLE
Use Clang 11 from Debian backports

### PR DESCRIPTION
**Pull request by agners**

### CODE REVIEW

**Comment by agners** [comment]
This is a prerequisite to move to Clang 11 for ESPHome. See also my comment in https://github.com/esphome/esphome/pull/1846#issuecomment-851016625

**Comment by agners** [comment]
I'd suggest to merge this and bump to 3.2.0 base container in the esphome repository right when starting the new dev cycle so there is enough time to deal with eventual fallout.

@OttoWinter does that sound reasonable to you?

**Comment by OttoWinter** [comment]
> I'd suggest to merge this and bump to 3.2.0 base container in the esphome repository right when starting the new dev cycle so there is enough time to deal with eventual fallout.

I'd also be ok with bumping straight away; because with the disabled checks it's unlikely any new PRs will fail

**Review by OttoWinter — APPROVED** [review]
LGTM, thanks!

**Comment by agners** [comment]
> I'd also be ok with bumping straight away; because with the disabled checks it's unlikely any new PRs will fail

Hm, just realized that since we don't version `esphome/esphome-lint` container, the CI pipelines of all branches will use the same new `esphome/esphome-lint:latest` container . So when merging https://github.com/esphome/esphome/pull/1846 it will lead to a new `esphome/esphome-lint:latest` with only `clang-11`...

So CI pipelines trying to use clang-7 will fail immediately from that point on :scream:. I guess that is pretty much every pull request currently open, as well as new pull requests on branches which don't have the script change in https://github.com/esphome/esphome/pull/1846 yet.

Or do I miss something?

I see three ways to fix this:
a) Version the `esphome/esphome-lint` container
b) Ship with both versions (clang-7 and clang-11)
c) Change the clang-tidy/clang-format scripts to use whatever clang version is shipped with the container. Then we can add the new ` .clang-tidy` file with the new exclusions (while still shipping clang-7 in the lint containers), wait for one release cycle or so until all branches have the new exceptions, then switch to clang-11.

IMHO, the cleanest way is a), but probably also requires most changes.

**Comment by OttoWinter** [comment]
Oh, you're right! That's not good.

I'd go with option a) personally, as this kind of issue is bound to happen again (should be as simple as changing the tag it's published under in the workflow).

Proposal:
- the `esphome/esphome-lint` image is versioned, with tags: `:latest`, `:1.0` (pinned version, independent of esphome release cycle)
- for now `esphome/esphome-lint` image should ship with both clang-7 and clang-11 images
- [GH build workflow](https://github.com/esphome/esphome/blob/dev/.github/workflows/docker-lint-build.yml#L36) is updated to push to the tags `:latest/:{version}` where version is some variable we set in that file (or set another way) -> add `--tag "esphome/esphome-lint:${TAG}" \` to `docker build`,  `docker push "esphome/esphome-lint:${TAG}"`, and `echo "TAG=1.0" >> $GITHUB_ENV` in a new `run:`
- Other workflows are updated to use the pinned version instead of `:latest`; can be a hardcoded value, iirc there's not a good way to have a variable shared across workflows.

Rationale:
- `esphome/esphome-lint:latest` should still ship `clang-7` for old workflows, as mentioned
- it should also ship `clang-11`, in order to not break any users who manually run `esphome/esphome-lint:latest` from their command line for testing
- lint image size is not a _huge_ concern, I imagine a whole clang/llvm will be quite big (<100)

**Pull request merged**
