### PR TITLE
Upgrade Platformio

### PR DESCRIPTION
**Pull request by Skaronator**
In conjunction with https://github.com/esphome/esphome/pull/1045

### CODE REVIEW

**Comment by Skaronator** [comment]
Not sure how to upgrade the Tags. I think only @OttoWinter can do that.

**Comment by glmnet** [comment]
can you hint me about the tag thing? is this related to docker building newer versions itself?

**Comment by Skaronator** [comment]
Yeah since this repo doesn't have any CI integration we'd need write access to the base images on the docker hub.

You'd build it locally and push it with a tag to the docker hub. For example here are the tags for the amd64 architecture base image: https://hub.docker.com/r/esphome/esphome-base-amd64/tags

After pushing the new base image we can update the tag here: https://github.com/esphome/esphome/blob/dev/docker/Dockerfile#L1

**Comment by glmnet** [comment]
Well, I don't have access to docker yet

**Comment by ivankravets** [comment]
Please replace `platformio==4.3.3` with `platformio` to avoid similar issues as https://github.com/esphome/issues/issues/1265

**Comment by TheLastGimbus** [comment]
Or `4.*.*`, to avoid forward incompatibility, if pio uses semantic version

**Comment by ivankravets** [comment]
You can use `"platformio<5"`. Nevertheless, we don't plan to modify our frozen CLI for build/flash in the next major versions.

**Comment by glmnet** [comment]
Regarding version stuff it is because we already faced problems with other libraries updating themselves and becoming incompatible with each other and or ESPHome. So an attempt to minimize this damage all versions where fixed and even some poorly versioned libraries got forked by Otto so that changes are more in control. This is a well known mechanism, it’s done in Hass a lot. 
I believe the problem here is just that there has no be a release in like 7 months and ESPHome nature is to relay much on development tools which depend on the dynamic internet.

**Comment by OttoWinter** [comment]
Hi! Yes I just released a new version with upgraded platformio to fix the problem.

As @glmnet said, we've had some situations where minor version changes in dependencies caused issues multiple times now. Some of those were mistakes in the dependency, but more often it's because ESPHome is hooking into internal parts of dependencies in some places. So we freeze all direct dependencies as is usual in the HA ecosystem.

For example: platformio is started in-process by esphome so that, among other things, we can patch a method that causes platformio to rebuild the entire project when files are added/removed. This is to make builds faster, and possible because we control the project files and know when to rebuild.

One could argue we should put those things upstream, but many of these patches are very specific to esphome's use cases, and wouldn't make sense upstream.

Then another option would be to fork the project (as we already do in some cases), but that's a lot of work and in effect that's exactly the same as using the base and patching it where necessary.

Plus, we ship docker containers with dependencies pre-installed (for hassio addons and users who don't want to install everything manually). We can't auto-upgrade dependencies there because then each container start would take ages.

**Pull request merged**
